### ISSUE TITLE
gridftp failures between ipv4 client and dual-stack server

### ISSUE THREAD

**Issue by okeeble** [gridcf/gct#102]
We have seen gridftp failures on sites with a dual-stack server and ipv4-only clients. In certain configurations (e.g. the new Dirac default), the client will use EPSV to get an IP address for the data connection. This returns an ipv6 address which, in a simple upload/download scenario, is unusable by the client.

While this behaviour is understandable (the client may be trying to establish a third-party transfer between two ipv6 capable servers) in reality it's causing problems.

We will provide a PR to give the option for EPSV to return an ipv4 address over an ipv4 connection.

Related DPM ticket : https://its.cern.ch/jira/browse/LCGDM-2817

**Comment by fscheiner** [comment]
Included in [GCT v6.2.20190906](https://github.com/gridcf/gct/releases/tag/v6.2.20190906).
