### ISSUE TITLE
configure issue in ubuntu 16.04

### ISSUE THREAD

**Issue by RubenGarcia** [gridcf/gct#111]
After installing
autoconf automake make libtool libltdl-dev gcc g++ patch openssl libssl-dev pkg-config
following the install instructions, 
configure gets:
.......
checking for netinet/tcp.h... yes
./configure: line 12398: syntax error near unexpected token `GLOBUS_COMMON,'
./configure: line 12398: `PKG_CHECK_MODULES(GLOBUS_COMMON, $PACKAGE_DEPS)'
configure: error: ./configure failed for xio/src

**Comment by RubenGarcia** [comment]
Ubuntu 18.04 seems to work, configure succeeds.

**Comment by ellert** [comment]
It looks like you have unexpanded autoconf macros in you configure script. The /usr/share/aclocal/pkg.m4 file that defines the PKG_CHECK_MODULES macro seems to not have been present when autoconf was run. This file is usually installed as part of the pkg-config package.

**Comment by fscheiner** [comment]
@RubenGarcia 
Just checking if this issue can be closed:
Does (1) installing `pkg-config` on Ubuntu 16.04 solve the initial issue or (2) is there something we need to do in the provided sources? Most likely not the latter, as it works for you on Ubuntu 18.04.

**Comment by RubenGarcia** [comment]
As you can see from my first message, pkg-config was already installed. I have run the instructions again with current gct and managed to compile it successfully, so this can be closed.

**Comment by fscheiner** [comment]
@RubenGarcia 
> As you can see from my first message, pkg-config was already installed.

Sorry, I overlooked that.

> I have run the instructions again with current gct and managed to compile it successfully, so this can be closed.

Strange. Just to be sure: you did perform your testing with a cloned repository and not an expanded full source tarball (e.g. https://repo.gridcf.org/gct6/sources/gct-6.2.1567772254.tar.gz), right?

**Comment by RubenGarcia** [comment]
Sorry, after one year has passed, so I don't remember if I used a cloned repository or a source tarball.
