### ISSUE TITLE
globus-domainname fails when GLOBUS_HOSTNAME set to IP address

### ISSUE THREAD

**Issue by RubenGarcia** [gridcf/gct#113]
echo $GLOBUS_HOSTNAME 
138.246.234.17
/usr/local/globus-6/bin/globus-domainname 
246.234.17

**Comment by RubenGarcia** [comment]
Fixed by https://github.com/gridcf/gct/pull/114, closing.

**Comment by fscheiner** [comment]
Fixed in [GCT 6.2.20201212 maintenance release](https://github.com/gridcf/gct/releases/tag/v6.2.20201212).
