### ISSUE TITLE
Issue with frontend/backend daemon setup. Connection and authorization OK but transfer pending forever.. 

### ISSUE THREAD

**Issue by UgoLopezElgart** [gridcf/gct#121]
Hi Grid community,

I'm trying to install Gridtfp on a dedicated server for the Euxdat H2020 research project.

I have a configuration with a frontend and a backend running on the same server. The frontend daemon (running as globus) is exposed to the outside on port udp:2811. The backend (running as root) accepts connections on localhost:2813 from the frontend. All inbound connections are allowed by the host over TCP:20000-25000.

When I try to list from an outside client with a registered user "euxdat_user"
`globus-url-copy -dbg -list gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/`

The client connects, authorizes but is pending forever when trying to execute the data transfer or list the folder. 

At the server level we see that the frontend received the request, forked, and established connection with the client and the backend. The backend has opened a tcp port to receive the data to the outside. 

> [root@gridftp-s1 grid-security]# netstat -apnt | grep globus
> 
> tcp        0      0 0.0.0.0:2811            0.0.0.0:*               LISTEN      3657/globus-gridftp
> tcp        0      0 0.0.0.0:21795           0.0.0.0:*               LISTEN      9279/globus-gridftp
> tcp        0      0 192.168.1.101:2811      80.158.4.251:44832      ESTABLISHED 9278/globus-gridftp
> tcp6       0      0 ::1:2813                :::*                    LISTEN      3649/globus-gridftp
> tcp6       0      0 ::1:20688               ::1:2813                ESTABLISHED 9278/globus-gridftp
> tcp6       0      0 ::1:2813                ::1:20688               ESTABLISHED 9279/globus-gridftp

![server](https://user-images.githubusercontent.com/61740333/75780916-894b2880-5d5c-11ea-8068-0e554bf74125.gif)

And nothing happens. I do not have additional info in the logs. Have you ever seen this kind of problem? Where can I go from there for further debugging? 

Thanks you in advance for any help,
Ugo

Full client log:

`globus-url-copy -dbg -list gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/`

> gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/
> debug: starting to feat gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/
> debug: connecting to gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/
> debug: response from gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> 220 gridftp-s1.euxdat.eu GridFTP Server 13.20 (gcc64, 1566483868-0) [Grid Community Toolkit 6.2] ready.
> 
> debug: authenticating with gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/
> debug: response from gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> 230 User euxdat_user logged in.
> 
> debug: sending command to gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> SITE HELP
> 
> debug: response from gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> 214-The following commands are recognized:
>     ALLO    APPE    REST    CWD     CDUP    DCAU    EPSV    FEAT
>     ERET    MDTM    STAT    ESTO    HELP    LIST    MODE    NLST
>     MLSC    MLSD    PASV    RNFR    MLSR    MLST    NOOP    OPTS
>     STOR    PASS    PBSZ    PORT    PROT    SITE    EPRT    RETR
>     SPOR    MFMT    SCKS    TREV    PWD     QUIT    SBUF    SIZE
>     SPAS    STRU    SYST    RNTO    TYPE    USER    LANG    MKD
>     RMD     DELE    CKSM    DCSC
> 214 End
> 
> debug: sending command to gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> FEAT
> 
> debug: response from gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> 211-Extensions supported
>  DSI remote-13.20
>  STORATTR
>  HTTP
>  DCSC P,D
>  MFMT
>  WHOAMI
>  AUTHZ_ASSERT
>  MLSR
>  MLSC
>  UTF8
>  LANG EN
>  DCAU
>  PARALLEL
>  SIZE
>  MLST Type*;Size*;Modify*;Perm*;Charset;UNIX.mode*;UNIX.owner*;UNIX.uid*;UNIX.group*;UNIX.gid*;Unique*;UNIX.slink*;X.count;
>  ERET
>  ESTO
>  SPAS
>  SPOR
>  REST STREAM
>  MDTM
>  PASV AllowDelayed;
> 211 End.
> 
> debug: sending command to gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> SITE CLIENTINFO scheme=gsiftp;appname="globus-url-copy";appver="10.5 (gcc64, 1566483868-0) [Grid Community Toolkit 6.2]";
> debug: response from gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> 250 OK.
> 
> debug: operation complete
> debug: starting to machine list gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/
> debug: sending command to gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> TYPE I
> debug: response from gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> 200 Type set to I.
> 
> debug: sending command to gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> PBSZ 1048576
> 
> debug: response from gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> 200 PBSZ=1048576
> 
> debug: sending command to gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> PASV
> 
> debug: response from gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> 227 Entering Passive Mode (127,0,0,1,86,255)
> 
> debug: sending command to gsiftp://gridftp-s1.euxdat.eu/home/euxdat_user/:
> MLSD /home/euxdat_user/

Frontend log:

> [9278] Tue Mar  3 13:49:00 2020 :: GFork functionality not enabled.:
> globus_gfork: GFork error: Env not set
> 

> [9278] Tue Mar  3 13:49:00 2020 :: Configuration read from /etc/gridftpd/gridftpd_frontend.conf.
> [9278] Tue Mar  3 13:49:00 2020 :: Server started in inetd mode.
> [9278] Tue Mar  3 13:49:00 2020 :: New connection from: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [CLIENT]: USER :globus-mapping:
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [SERVER]: 331 Password required for :globus-mapping:.
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [CLIENT]: PASS
> [9278] Tue Mar  3 13:49:00 2020 :: [globus_l_gfs_default_brain_select_nodes
> ] enter[9278] Tue Mar  3 13:49:00 2020 :: DN /O=Grid/OU=GlobusTest/OU=gridftp-s1.euxdat.eu/OU=Euxdat Cloud GridFTP CA/CN=Euxdat User successfully authorized.
> [9278] Tue Mar  3 13:49:00 2020 :: User euxdat_user successfully authorized.
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [CLIENT]: PASS
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [SERVER]: 230 User euxdat_user logged in.
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [CLIENT]: SITE HELP
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [SERVER]: 214-The following commands are recognized:
>     ALLO    APPE    REST    CWD     CDUP    DCAU    EPSV    FEAT
>     ERET    MDTM    STAT    ESTO    HELP    LIST    MODE    NLST
>     MLSC    MLSD    PASV    RNFR    MLSR    MLST    NOOP    OPTS
>     STOR    PASS    PBSZ    PORT    PROT    SITE    EPRT    RETR
>     SPOR    MFMT    SCKS    TREV    PWD     QUIT    SBUF    SIZE
>     SPAS    STRU    SYST    RNTO    TYPE    USER    LANG    MKD
>     RMD     DELE    CKSM    DCSC
> 214 End
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [CLIENT]: FEAT
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [SERVER]: 211-Extensions supported
>  DSI remote-13.20
>  STORATTR
>  HTTP
>  DCSC P,D
>  MFMT
>  WHOAMI
>  AUTHZ_ASSERT
>  MLSR
>  MLSC
>  UTF8
>  LANG EN
>  DCAU
>  PARALLEL
>  SIZE
>  MLST Type*;Size*;Modify*;Perm*;Charset;UNIX.mode*;UNIX.owner*;UNIX.uid*;UNIX.group*;UNIX.gid*;Unique*;UNIX.slink*;X.count;
>  ERET
>  ESTO
>  SPAS
>  SPOR
>  REST STREAM
>  MDTM
>  PASV AllowDelayed;
> 211 End.
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [CLIENT]: SITE CLIENTINFO scheme=gsiftp;appname="globus-url-copy";appver="10.5 (gcc64, 1566483868-0) [Grid Community Toolkit 6.2]";
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [SERVER]: 250 OK.
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [CLIENT]: TYPE I
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [SERVER]: 200 Type set to I.
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [CLIENT]: PBSZ 1048576
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [SERVER]: 200 PBSZ=1048576
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [CLIENT]: PASV
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [SERVER]: 227 Entering Passive Mode (127,0,0,1,85,35)
> [9278] Tue Mar  3 13:49:00 2020 :: ecs-80-158-4-251.reverse.open-telekom-cloud.com:44832: [CLIENT]: MLSD /home/euxdat_user/

Backend log:

> [9279] Tue Mar  3 13:49:00 2020 :: GFork functionality not enabled.:
> globus_gfork: GFork error: Env not set
> 
> [9279] Tue Mar  3 13:49:00 2020 :: Configuration read from /etc/gridftpd/gridftpd_backend_#1.conf.
> [9279] Tue Mar  3 13:49:00 2020 :: Server started in inetd mode.
> [9279] Tue Mar  3 13:49:00 2020 :: New connection from: localhost:20688
> 

OS version:
> CentOS Linux release 7.7.1908 (Core)

Package versions:

> globus-authz.x86_64                4.3-1.el7                @epel
> globus-authz-callout-error.x86_64  4.1-1.el7                @epel
> globus-callout.x86_64              4.2-1.el7                @epel
> globus-common.x86_64               18.5-1.el7               @epel
> globus-common-devel.x86_64         18.5-1.el7               @epel
> globus-common-progs.x86_64         18.5-1.el7               @epel
> globus-ftp-client.x86_64           9.2-1.el7                @epel
> globus-ftp-control.x86_64          9.4-1.el7                @epel
> globus-gass-copy.x86_64            10.5-1.el7               @epel
> globus-gass-copy-progs.x86_64      10.5-1.el7               @epel
> globus-gass-transfer.x86_64        9.1-1.el7                @epel
> globus-gfork.x86_64                5.0-1.el7                @epel
> globus-gridftp-server.x86_64       13.20-1.el7              @epel
> globus-gridftp-server-control.x86_64
> globus-gridftp-server-progs.x86_64 13.20-1.el7              @epel
> globus-gsi-callback.x86_64         6.1-1.el7                @epel
> globus-gsi-cert-utils.x86_64       10.3-1.el7               @epel
> globus-gsi-credential.x86_64       8.1-1.el7                @epel
> globus-gsi-openssl-error.x86_64    4.1-1.el7                @epel
> globus-gsi-proxy-core.x86_64       9.4-1.el7                @epel
> globus-gsi-proxy-ssl.x86_64        6.2-1.el7                @epel
> globus-gsi-sysconfig.x86_64        9.2-3.el7                @epel
> globus-gss-assist.x86_64           12.2-1.el7               @epel
> globus-gssapi-error.x86_64         6.1-1.el7                @epel
> globus-gssapi-gsi.x86_64           14.11-1.el7              @epel
> globus-io.x86_64                   12.2-1.el7               @epel
> globus-openssl-module.x86_64       5.1-1.el7                @epel
> globus-xio.x86_64                  6.2-1.el7                @epel
> globus-xio-gsi-driver.x86_64       5.2-1.el7                @epel
> globus-xio-pipe-driver.x86_64      4.1-1.el7                @epel
> globus-xio-popen-driver.x86_64     4.1-1.el7                @epel
> globus-xio-udt-driver.x86_64       2.2-1.el7                @epel

GSI configuration:

> MIN_TLS_PROTOCOL=TLS1_VERSION_DEPRECATED
> MAX_TLS_PROTOCOL=0
> NAME_COMPATIBILITY=STRICT_RFC2818
> CIPHERS=HIGH
> SERVER_CIPHER_ORDER=true
> BACKWARD_COMPATIBLE_MIC=true
> ACCEPT_BACKWARD_COMPATIBLE_MIC=true
> VHOST_CRED_OWNER=root

Frontend started as "globus" with:

`/usr/sbin/globus-gridftp-server -c /etc/gridftpd/gridftpd_frontend.conf -C /etc/gridftpd/gridftpd_frontend.conf.d -exec /usr/sbin/globus-gridftp-server -pidfile /var/run/gridftpd/gridftpd_frontend.pid -hostname gridftp-s1.euxdat.eu -port 2811 -remote-nodes gridftp-s1.euxdat.eu:2813 -logfile /var/log/gridftpd/gridftpd_frontend.log -log-transfer /var/log/gridftpd/gridftpd_frontend.netlog -no-detach -config-base-path /`

Frontend configuration:

> 
> daemon 1
> auth_level 0
> log_filemode 0644
> disable_usage_stats 1
> blocksize 16M
> control_interface 0.0.0.0
> ipc_interface 127.0.0.1

Backend started as "root" with:

` /usr/sbin/globus-gridftp-server -c /etc/gridftpd/gridftpd_backend_#1.conf -C /etc/gridftpd/gridftpd_backend_#1.conf.d -exec /usr/sbin/globus-gridftp-server -pidfile /var/run/gridftpd/gridftpd_backend_#1.pid -hostname gridftp-s1.euxdat.eu -port 2813 -ipc-allow-from gridftp-s1.euxdat.eu -logfile /var/log/gridftpd/gridftpd_backend_#1.log -log-transfer /var/log/gridftpd/gridftpd_backend_#1.netlog -no-detach -config-base-path /`

Backend configuration:

> daemon 1
> auth_level 2
> log_level ALL
> log_filemode 0644
> disable_usage_stats 1
> data_node 1
> blocksize 16M

System level config:

> GRIDFTPD_BIN="/usr/sbin/globus-gridftp-server"
> GRIDFTPD_LD_LIBRARY_PATH="/usr/sbin/../lib"
> GLOBUS_LOCATION="/usr/sbin/.."
> GRIDFTPD_PIDFILES_PATH="/var/run/gridftpd"
> GRIDFTPD_CONFIG_BASE_PATH="/etc/gridftpd"
> 
> GRIDFTPD_HOST_FQDN="gridftp-s1.euxdat.eu"
> GRIDFTPD_TCP_PORT_RANGE="20000,25000"
> GRIDFTPD_TCP_SOURCE_RANGE="20000,25000"
> 
> GRIDFTPD_GSI_CONFIG_BASE_PATH="/etc/grid-security"
> GRIDFTPD_GRIDMAPFILE="/etc/grid-security/grid-mapfile"
> GRIDFTPD_X509_CERT_DIR="/etc/grid-security/certificates"
>

**Comment by maarten-litmaath** [comment]
Hi all,
the trouble is shown in this line:

227 Entering Passive Mode (127,0,0,1,86,255)

The server thinks its own address is 127.0.0.1, i.e. localhost,
surely due to a bad entry in /etc/hosts: mind that 127.0.0.1
must _only_ be used for localhost, never the real DNS name...

________________________________

**Comment by UgoLopezElgart** [comment]
Much thanks!

I have set manually the data_interface value to the IP address in the backend config and its now working.

> 
> daemon 1
> auth_level 2
> log_level ALL
> log_filemode 0644
> disable_usage_stats 1
> data_node 1
> blocksize 16M
> **data_interface N.N.N.N**


I add to keep the bad entry in /etc/hosts because it was used by the frontend to connect wih the backend. It is overrode by the backend config
