### ISSUE TITLE
how XIO works with tar?

### ISSUE THREAD

**Issue by Jin-Chao** [gridcf/gct#124]
I  downloaded gct and tried to enable XIO with tar using the following settings:

 1) globus-gridftp-server -aa -fs-whitelist popen,file,ordering -popen-whitelist tar:/usr/bin/tar

2) globus-url-copy -pipe /usr/bin/tar

But I got the following error:
------------------------------------
 error: globus_ftp_client: the server responded with an error
500 500-Command failed. : globus_xio: popened program exited with an error (exit code: 2):
500-/usr/bin/tar: You must specify one of the `-Acdtrux' or `--test-label'  options
500-Try `/usr/bin/tar --help' or `/usr/bin/tar --usage' for more information.
500-
500 End.
------------------------------------

Wondering how to set XIO for using tar? 

Thanks

**Comment by msalle** [comment]
Hi,
I'm not sure what you're trying to do exactly and have no personal experience with using globus-url-copy using the pipe option, but calling `tar` without arguments gives this error message.
From the options in the [documentation for globus-url-copy](https://gridcf.org/gct-docs/latest/gridftp/user/index.html#globus-url-copy) I would think you probably need only `-dst-pipe` with the correct `-x` flags, probably something like `tar -xf -`.

**Comment by fscheiner** [comment]
@Jin-Chao 
Do you need any further assistance or can this issue be closed?

**Comment by Jin-Chao** [comment]
@fscheiner 
Sorry for late response. 
Thank you very much for your help. We have reviewed globus-dir-copy, and it worked well. Please close this thread.

**Comment by fscheiner** [comment]
@Jin-Chao 
Glad we could work it out.

**Comment by fscheiner** [comment]
@Jin-Chao @msalle 
https://web.archive.org/web/20100612224141/http://www.mcs.anl.gov/~bresnaha/Stretch/ has some very interesting additional examples that use the "popen" functionality. Might come in handy sometime. :-)
