### ISSUE TITLE
gsi-openssh for Debian

### ISSUE THREAD

**Issue by caela** [gridcf/gct#170]
For 7.5 I managed to compile a debian package for gsi-openssh by omitting part of the patches given in packaging/debian/gsi-openssh/debian/patches/series (because they were redundant anyway). I see those patches are still there and 
make gsi-openssh-deb
still doesn't work straight away.
Maybe someone feels like fixing this..

**Comment by fscheiner** [comment]
GSI-OpenSSH w/HPN packages for Debian GNU/Linux 11 based on OpenSSH 8.4p1 are now  available from the openSUSE Build Service:

https://build.opensuse.org/package/show/home:frank_scheiner:gsi-openssh-debian-11/gsi-openssh

Repo:
https://download.opensuse.org/repositories/home:/frank_scheiner:/gsi-openssh-debian-11/Debian_11/

Follow the instructions on https://en.opensuse.org/openSUSE:Build_Service_Debian_builds#Configuring_sources.list to allow installations from this repository. The needed key is https://download.opensuse.org/repositories/home:/frank_scheiner:/gsi-openssh-debian-11/Debian_11/Release.key.

**Comment by fscheiner** [comment]
Updated the previous comment.

**Comment by rapier1** [comment]
@fscheiner By the way, which patch set is gsissh using at this point for current releases?
