### ISSUE TITLE
fail to compiler gct-6.2 because of openssl

### ISSUE THREAD

**Issue by longlong10086** [gridcf/gct#175]
I compiled gct6.2 on redhat6.4 before, but it failed. 

##uname -a
Linux ln4 2.6.32-358.123.4.el6.x86_64 #11 SMP Mon Jan 5 10:51:32 CST 2015 x86_64 x86_64 x86_64 GNU/Linux

##openssl
openssl-devel-1.0.0-27.el6.x86_64

##commands
autoreconf -i

./configure  --enable-myproxy  \
--enable-gram5-{server,lsf,sge,slurm,condor,pbs,auditing}  \
--prefix=/THL7/home/globus/softs/gct-6.2

make

#####＃＃＃＃＃＃＃＃＃＃＃＃＃＃#
**step  configure**  .

checking OpenSSL header version... 10000003 (OpenSSL 1.0.0 29 Mar 2010)
checking OpenSSL library version... configure: error: OpenSSL >= 1.0.1 required (have "10000003 (OpenSSL 1.0.0-fips 29 Mar 2010)")
configure: error: ./configure.gnu failed for gsi_openssh/source
#######################################

Then  I tried to compiler openssl1.1.1l / openssl3.0 (and used env LD_LIBRARY_PATH,eg) ,
the error disapped  but  got other errors at **step  make.**

###using openssl1.1.1l

verify_mic.c: 在函数‘globus_l_gss_verify_mic_new’中:
verify_mic.c:489: 错误：‘struct gss_ctx_id_desc_struct’没有名为‘mac_read_sequence’的成员
verify_mic.c:492: 错误：‘struct gss_ctx_id_desc_struct’没有名为‘mac_read_sequence’的成员
verify_mic.c:501: 错误：‘struct gss_ctx_id_desc_struct’没有名为‘mac_read_sequence’的成员
verify_mic.c:514: 错误：‘struct gss_ctx_id_desc_struct’没有名为‘mac_read_sequence’的成员
make[5]: *** [libglobus_gssapi_gsi_la-verify_mic.lo] 错误 1
make[5]: Leaving directory `/home/test/softs/pkgs/gct-github/gsi/gssapi/source/library'
make[4]: *** [all] 错误 2

####using  openssl3.0
proxycertinfo.c:50: 错误：与‘PROXYCERTINFO_dup’类型冲突
proxycertinfo.h:155: 附注：‘PROXYCERTINFO_dup’的上一个声明在此
make[4]: *** [proxycertinfo.lo] 错误 1
make[4]: Leaving directory `/home/test/softs/pkgs/gctgithub/gct-github/gsi/proxy/proxy_ssl/source/library'
make[3]: *** [all-recursive] 错误 1

How to fix this error.Hope to get your help.

**Comment by maarten-litmaath** [comment]
Hi,
please retry with "LANG=C" in your environment, so that at least the error messages may become comprehensible to us...

**Comment by fscheiner** [comment]
@longlong10086: Could you please add the requested information?
