### ISSUE TITLE
Can't install gct-toolkit release gct-6.2.20210826

### ISSUE THREAD

**Issue by ortegajosant** [gridcf/gct#176]
I tried to install the GCT following this [guide](https://gridcf.org/gct-docs/6.2/admin/quickstart/index.html) for Ubuntu 20.04 and I downloaded the package from [here](https://downloads.globus.org/toolkit/gt6/stable/installers/repo/deb/index.html) because the given [link](http://www.globus.org/ftppub/gt6/installers/repo/globus-toolkit-repo_latest_all.deb) in the guide doesn't work.

So, I installed it and then I ran:
```
sudo apt-get update
sudo apt-get install globus-gridftp globus-gram5 globus-gsi myproxy myproxy-server myproxy-admin
```

But it shows:
```
E: Failed to locate package globus-gridftp
E: Failed to locate package globus-gram5
E: Failed to locate globus-gsi package
```

So, I tried to install the toolkit from the source, I did the following steps:

1. Download the [source](https://github.com/gridcf/gct/archive/refs/tags/v6.2.20210826.tar.gz)
2. Run `tar -xzvf gct-6.2.20210826.tar.gz`
3. Run `autoreconf -i`

I already installed all the prerequisites described in the `INSTALL.md` file.
But when I run the step 3, it shows a big error such as:

```
/usr/bin/m4:configure.ac:23: cannot open `globus-version.inc': No such file or directory
Unable to update dirt.sh
fatal: not a git repository (or no parent at mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or no parent at mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./packaging/git-dirt-filter: 8: cannot open /branch.def: No such file
fatal: not a git repository (or no parent at mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or no parent at mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or no parent at mount point /)
...
...
...
fatal: not a git repository (or no parent at mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or no parent at mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or no parent at mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./packaging/git-dirt-filter: 8: cannot open /branch.def: No such file
fatal: not a git repository (or no parent at mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
+ cat
/usr/bin/m4:configure.ac:34: cannot open `gct-current-tag.inc': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
```

What am I doing wrong?
I really appreciate any help.

**Comment by msalle** [comment]
Hi Jose,
first of all, the package names you try to install are not correct. I'd say you need for example globus-gridftp-server-progs.
https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=globus
for the Ubuntu package names. I don't know what type of service you're trying to install so can't really say which ones you'd need.
Secondly, the links in https://gridcf.org/gct-docs/6.2/admin/quickstart/index.html#q-prereq are wrong. Thanks for pointing that out, we'll make an issue of that and fix it.
Thirdly, for installing from source, you should use the source installer, look for `Download URL for GCT full source tarball` on the release page https://github.com/gridcf/gct/releases/tag/v6.2.20210826 Starting from that tarball should work fine, no need to run `autoreconf`, you can just run directly `configure`
You can also do a `git clone` and checkout the tag, but the zip or tarball from the release page is currently not supported due to this issue you bumped into.

**Comment by msalle** [comment]
Actually, for the first point see https://github.com/gridcf/gct-docs/issues/14#issuecomment-628615248

**Comment by ortegajosant** [comment]
Hi thank you for your response,
So, is it necessary to install all the packages listed in https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=globus? I want to create an infrastructure with a lot of containers that will read small files continuously controlled by users, etc. So I guess installing `globus-gram-job-manager globus-gridftp-server-progs globus-simple-ca globus-gsi-cert-utils-progs myproxy myproxy-server myproxy-admin` will install all the dependencies needed or should I add another?

**Comment by maarten-litmaath** [comment]
Hola Jose,
please be aware that the GCT is maintained at best-effort level and for some components we do not really have the expertise to help debug things.  What is more, the biggest users of this middleware are steadily moving away from it --> the signs are not good for new projects to start depending on it.  You may want to look for alternative SW stacks to implement the functionality you need...

**Comment by ortegajosant** [comment]
> Hola Jose, please be aware that the GCT is maintained at best-effort level and for some components, we do not really have the expertise to help debug things. What is more, the biggest users of this middleware are steadily moving away from it --> the signs are not good for new projects to start depending on it. You may want to look for alternative SW stacks to implement the functionality you need...

Oh, that's good information, thank you for that.

**Comment by ortegajosant** [comment]
@maarten-litmaath Do you know which SW they are migrating to?

**Comment by maarten-litmaath** [comment]
Hola Jose,
the biggest users are the CERN LHC experiments on WLCG plus related communities on EGI, OSG and NorduGrid. Years ago we already stopped using GRAM and today we rely on HTCondor and ARC for grid jobs.  The GridFTP protocol has mostly been phased out on WLCG in the last 12 months, being replaced with HTTP+WebDAV and Xrootd.  That leaves us with GSI and MyProxy for X509, which we have started replacing with JWT for job submissions, but it will take a few years still to weed out X509 completely.  Now, the GCT is being maintained by just a few people whose organizations still need to care about some parts of this SW for the time being --> as soon as the SW becomes mostly irrelevant for a contributing institution, its support efforts will probably be stopped.

What are you trying to set up?

**Comment by fscheiner** [comment]
Should be fixed with https://github.com/gridcf/gct-docs/pull/27/.

**Comment by fscheiner** [comment]
@ortegajosant:
Is your initial request solved with the changes from https://github.com/gridcf/gct-docs/pull/27 in place now? Please see https://gridcf.org/gct-docs/6.2/admin/quickstart/index.html again for the updated content.

**Comment by ortegajosant** [comment]
Thank you @fscheiner

**Comment by fscheiner** [comment]
You're welcome.
