### ISSUE TITLE
DNS error on repo.gridcf.org

### ISSUE THREAD

**Issue by chrisburr** [gridcf/gct#194]
For the past few hours I've been trying to download the tarball for the latest release but it seems to be broken with a DNS issue:

https://repo.gridcf.org/gct6/sources/gct-6.2.1629922860.tar.gz

Would someone be able to take a look ot point me to an alternative source?

**Comment by fscheiner** [comment]
@chrisburr: Thanks for reporting.

@matyasselmeci: Could you please have a look at this issue?

**Comment by chrisburr** [comment]
This seems to have been fixed now, thanks to whoever intervened! 🍰

**Comment by fscheiner** [comment]
Thanks for the update.
