### ISSUE TITLE
pipeline doesn't work: ERROR: too many url strings specified

### ISSUE THREAD

**Issue by yanzhibo-nju** [gridcf/gct#203]
I want to use the pipeline feature of gridftp. I run `globus-gridftp-server` as a daemon in two servers and use `globus-url-copy` and `-pp` or `-pipeline` to achieve **third-party** transfer at one of the servers. But errors occur: **too many url strings specified**. How can I use the pipeline feature? Thanks.

**Comment by yanzhibo-nju** [comment]
```
[root@bl197 ~]# globus-gridftp-server -version
globus_gridftp_server: 13.24 (1653033972-1)
```
```
[root@bl197 ~]# globus-url-copy -version
globus-url-copy: 10.12
```

**Comment by fscheiner** [comment]
@yanzhibo-nju:
Please also provide the used command.

**Comment by yanzhibo-nju** [comment]
Server1: `globus-gridftp-server -control-interface 192.168.110.1 -aa -p 60060 - anonymous-user 1040 -home-dir /home/data -auth-level 0 -allow-root`

Server2: `globus-gridftp-server -control-interface 192.168.110.2 -aa -p 60060 - anonymous-user 1040 -home-dir /home/data -auth-level 0 -allow-root`

then still on server2: `globus-url-copy -vb -pp 2 -r ftp://192.168.110.1:60060/home/dtn/200MB/ ftp://192.168.110.2:60060/home/dtn/200MB/`,where `200MB` is my file folder.

**Comment by yanzhibo-nju** [comment]
Hi fscheiner, thank you very much for your reply. I have tried the two ways, `-pp` as a flag and `-ppq` with an argument, they both work! But I still use `ftp://` rather than  `gsi:ftp//`, I believe for `gsi:ftp` it will work as well.

Thanks for you help again!

**Comment by fscheiner** [comment]
@yanzhibo-nju 
Good to know and thanks for your report.
