### ISSUE TITLE
autoreconf failure: files not found

### ISSUE THREAD

**Issue by uihsnv** [gridcf/gct#206]
I am attempting to install from source, and when I run `autoreconf -i`, this is what I get:

```
$ autoreconf -i 
/usr/bin/m4:configure.ac:23: cannot open `globus-version.inc': No such file or directory
Unable to update dirt.sh
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./packaging/git-dirt-filter: line 8: /branch.def: No such file or directory
fatal: not a git repository (or any parent up to mount point /home)
.
.
.
./packaging/git-dirt-filter: line 8: /branch.def: No such file or directory
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
+ cat
/usr/bin/m4:configure.ac:34: cannot open `gct-current-tag.inc': No such file or directory
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
```

It seems to be unable to find "globus-version.inc" and "gct-current-tag.inc". It also seems to this is a git directory. I am not sure why. I attempted this using the ".tar.gz" sources of the two latest releases.

Am I doing something wrong?

**Comment by fscheiner** [comment]
> I am attempting to install from source, and when I run autoreconf -i, this is what I get:
> [...]
> It seems to be unable to find "globus-version.inc" and "gct-current-tag.inc". It also seems to this is a git directory. I am not sure why. I attempted this using the ".tar.gz" sources of the two latest releases.

Running `autoreconf -i` requires information from the git repository. When using the tar.gz or zip downloads, this is missing. Unfortunately these downloads are always "attached" to releases although they are not useful.

You have two options if you want to build it from source:

1. Use the source installer available on https://repo.gridcf.org/gct6/sources/ and named e.g. `gct-6.2.1653033972.tar.gz` for the latest version corresponding to the latest release of the GCT. It is already `autoreconf`ed and you can directly start with `./configure`.

2. Clone the whole repo (e.g. `git clone https://github.com/gridcf/gct.git`) and work from there, starting with `autoreconf -i`. You can follow the process we are using for our CI builds and outlined in https://github.com/gridcf/gct/blob/master/travis-ci/build_and_test.sh.
