### ISSUE TITLE
Bug in /etc/init.d/globus-gridftp-server affects Pacemaker

### ISSUE THREAD

**Issue by adorsey-NOAA** [gridcf/gct#47]
I've found a bug in the init script for the GridFTP server in current versions of the globus-gridftp-server-progs RPM for RHEL 6.  Not sure if that's been fixed in your fork, but I wanted to make you aware in case.

Whenever this script is run with the status option (/etc/init.d/globus-gridftp server status) the status is correctly reported, but the return code is always 0.  This isn't a problem until someone tries to use Pacemaker to manage GridFTP services.  The incorrect return code causes Pacemaker to always think the GridFTP service is running, so it never gets started.

The following hack makes the script return an exit value correctly when the status parameter is passed.

```
--- globus-gridftp-server.orig  2018-08-07 22:56:34.217826950 +0000
+++ globus-gridftp-server       2018-08-07 22:58:17.035903704 +0000
@@ -139,6 +139,7 @@
        ;;
     status)
        status
+       rc=$?
        ;;
     restart | force-reload)
        restart
```

**Comment by ellert** [comment]
This was addressed by merging the corresponding fix from the old GT upstream.
