### ISSUE TITLE
tarballs on repo.gridcf.org

### ISSUE THREAD

**Issue by fscheiner** [gridcf/gct#52]
## Wrong content type ##

All tarballs seem to have a wrong content type:

![wrong-content-type-for-tarballs](https://user-images.githubusercontent.com/4545897/45823697-8b4b3400-bcee-11e8-9829-25ef283d4f0f.jpg)

...which makes the web browser trying to display them instead of downloading them. I think this also makes a problem when downloading them via "Save link as...", as the SHA512 hash for the resulting downloaded file differs from the hash value that is served from repo.gridcf.org:

```
$ sha512sum globus_authz-4.1.tar.gz 
bed65b664a0b00d24753a78ab7a088dd100d0b4db8c6a6be75b22f063f0c9706c200894557f409b2e63af4afef46bd5747ec37b59efda09b1de02e355f7fc04a  globus_authz-4.1.tar.gz

$ cat globus_authz-4.1.tar.gz.sha512 
b86a6f897e75b5389dea6b080bb7b01e78014a2a57b17f4793a6a34e0634e344c259cbe9a8bf0bf8411f747c9b429b6a92c3581e4a9fd0049a1653217c2b76e0  globus_authz-4.1.tar.gz

$ sha512sum -c globus_authz-4.1.tar.gz.sha512
globus_authz-4.1.tar.gz: FAILED
sha512sum: WARNING: 1 computed checksum did NOT match
```

## HTTP version of download site ##

Is there still a need for the HTTP version, because if not, I'd recommend to redirect to the HTTPS version instead to avoid any unwanted insecure downloads.

**Comment by brianhlin** [comment]
Hi @fscheiner, @djw8605 has updated the web server config to address the content type. How does it look for you now?

**Comment by fscheiner** [comment]
The content type is now correct and downloaded files are no longer corrupted:
```
$ sha512sum -c globus_authz-4.1.tar.gz.sha512
globus_authz-4.1.tar.gz: OK
```

**Comment by fscheiner** [comment]
@brianhlin @djw8605 
Just remembered this issue. As the content type is correct since September 20th, what about the second part of https://github.com/gridcf/gct/issues/52#issue-362209857, i.e. redirecting HTTP to HTTPS, so users do not download files unencrypted?

**Comment by matyasselmeci** [comment]
Thanks for the reminder; I'll talk to the admin.

**Comment by matyasselmeci** [comment]
Turns out this needs to be done at the cloudflare level. Paging @bbockelm ...

**Comment by brianhlin** [comment]
Cloudflare access has been transferred to me (I will also give @matyasselmeci access) and I've enabled the HTTP -> HTTPS redirect. It looks like it's working on our end, how does it look to you @fscheiner ?

**Comment by fscheiner** [comment]
@brianhlin 
Thanks, I tested with HTTP URLs and `Firefox` and `wget` and both now get redirected to HTTPS. So works like a charm now. Great! :-)

I'm closing this issue now.
