### ISSUE TITLE
Doing a PUT and then a GET through the same handle freezes the process

### ISSUE THREAD

**Issue by chaen** [gridcf/gct#81]
Following suggestion of @msalle , I am opening a new bug here for the issue reported here: https://github.com/globus/globus-toolkit/issues/57

**Comment by paulmillar** [comment]
There is a corresponding dCache issue: dCache/dcache/issues/4830.

My tests with two dCache endpoints (one running v3.2, the other the currently unreleased v5.2) and with two globus-url-copy versions (v9.23 and v10.4) have failed to recreate the problem.  Therefore, my best guess is that this is a site-local issue involving IN2P3, or there is some other factor of which we are currently unaware.

**Comment by fscheiner** [comment]
> There is a corresponding dCache issue: [dCache/dcache/issues/4830.](https://github.com/dCache/dcache/issues/4830)

Following up on the dCache issue I assume this issue (gridcf/gct#81) was invalid for the GCT, as was the issue https://github.com/globus/globus-toolkit/issues/57 for the Globus Toolkit. Therefore I'm closing it now. Still good that these issues helped in solving the problem. :-)

****

@chaen @msalle @ellert @matyasselmeci 
I just keep wondering why `globus-url-copy` v10.4 (from the GCT) did hit that issue and `globus-url-copy` v9.28 (from the Globus Toolkit) did not (as per https://github.com/globus/globus-toolkit/issues/57#issuecomment-490465448). Maybe an internal default was changed? For an investigation we would need more information, though.

"...but maybe not so important..."
_(from Famous Last Words (Final Edition))_ ;-)

**Comment by chaen** [comment]
At this point, I'd tend to agree with the `Famous Last Words` :-)
