### ISSUE TITLE
gct fails to build with Python 3.8

### ISSUE THREAD

**Issue by stratakis** [gridcf/gct#87]
Currently on Fedora we are testing rebuilding the distro against Python 3.8 and the net manager is one of the packages that failed to build from source.

This happens when the --enable-python option is given, due to `python3-config --libs` [invocation](https://github.com/gridcf/gct/blob/9ded40fc704c121fd19e416a49084143dcfb9a25/gridftp/net_manager/configure.ac#L32) requiring also the `--embed` flag, with Python 3.8, in order to link the application to libpython.

As this is applicable only for 3.8, using the same flag on lesser versions will make the compilation fail as well, so a conditional would be required there. [More info](https://docs.python.org/3.8/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build).

Full build log attached
[build.log.gz](https://github.com/gridcf/gct/files/3249030/build.log.gz)

**Comment by fscheiner** [comment]
Included in [GCT v6.2.20190906](https://github.com/gridcf/gct/releases/tag/v6.2.20190906).
