### ISSUE TITLE
[BUG] GRAM job manager error because of the non-standard installation path "\"

### ISSUE THREAD

**Issue by iWangJiaxiang** [gridcf/gct#93]
## Description

Hello dear developers,

This is a bug that occurs when use the non-standard installation path (not `\`).

I tried to compile and install GCT on a custom path (not standard path `\`) but I got errors when running `globus-job-run`. The error looks like below:

>GRAM Job failed because the job manager detected an invalid script status (error code 25)

## Reproduction

Just compile and install GCT to a custom path and run `globus-job-run` after proper configuration.

## Research

After referring the official [doc](https://gridcf.org/gct-docs/latest/gram5/pi/index.html#gram5-errors-table) I found more details:

Error Code | Reason | Possible Solutions
:-: | :-: | :-:
25 | the job manager detected an invalid script status | Check job manager logs. This is likely a bug in the LRM script.

I followed the [doc](https://gridcf.org/gct-docs/latest/gram5/user/index.html#_diagnosing_lrm_errors) to diagnose LRM error. When I  run the command `globus-job-manager-script.pl -h`, I got nothing on `Installed managers`.

According to the `globus-job-manager-script.pl` perl script, `-h` option should have listed all install LRM managers but I got nothing.  The relative code is as below:

```
if ($help)
{
    my $managers;
    print "USAGE: $0 -m MANAGER -f FILE -c COMMAND\n";
    print "Installed managers:";
    foreach (<$perlmoduledir/Globus/GRAM/JobManager/*.pm>)
    {
        my $manager = $_;
        chomp($manager);
        $manager =~ s|.*/||;
        $manager =~ s|\.pm$||;
        print " $manager";
    }
    print "\n";
    exit(0);
}
```

After more review of the script, I found the reason was the `$perlmoduledir` variable which should have correct path but not (the value was just `/perl`). That's because the initialization of  `$perlmoduledir` needs to contain the value of  $libdir` as the code below.

    $perlmoduledir = "${libdir}/perl";

However, the `$libdir` is defined but a value is never assigned to it. So the `$perlmoduledir` would never get correct path to locate LRM scripts.

## Reason

`$perlmoduledir` not properly assigned because of un-assigned variable `$libdir`.

I checked line 49 in the [source file](https://github.com/gridcf/gct/blob/58a9ae54420152ae5e21eb536200f01295a36e74/gram/jobmanager/scripts/globus-job-manager-script.pl.in) and the code is `$perlmoduledir = "@perlmoduledir@";`. This mighit be fixed in the initialization of GCT installation.

## Solution

For now my workaround is manually assigning the lib directory to `$libdir` before the assignment of `$perlmoduledir` in the file `globus-job-manager-script.pl`. Just like below:

```
...
$libdir = "/path/to/globus/lib";
$perlmoduledir = "${libdir}/perl";
...
```

Hope this could help~

**Comment by fscheiner** [comment]
Included in GCT v6.2.20190906.
